### ISSUE TITLE
Add license information

### ISSUE THREAD

**Issue by vazhnov** [sbelectronics/ups#1]
Hello!

I found link to this project from https://hackaday.com/2020/11/05/a-super-ups-for-the-pi/

Could you please add information about license of this repository — is it allowed to copy, change and use code in any purpose?
It would be great to see any popular open source license.

**Comment by sbconsulting** [comment]
Added a LICENSE.md. I tried to pick one that seemed reasonably permissive.

**Comment by sbelectronics** [comment]
Added a LICENSE.md. I tried to pick one that seemed reasonably permissive.

**Comment by vazhnov** [comment]
Creative Commons Attribution-ShareAlike 3.0 — great!
And interesting addition :)
Thank you!
